//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProgress.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int ID_session { get; set; }
        public string Subject { get; set; }
        public int Teacher { get; set; }
        public int Group { get; set; }
        public int Student { get; set; }
        public string TypeOfCertification { get; set; }
        public string DueDate { get; set; }
        public string Grade { get; set; }
    
        public virtual Group Group1 { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
